### ISSUE TITLE
大佬，最近有更新计划吗

### ISSUE THREAD

**Issue by overbai** [sollrei/bitcron-theme#1]
大佬，最近有更新计划吗？

**Comment by sollrei** [comment]
> 大佬，最近有更新计划吗？

暂时应该没有吧

**Comment by overbai** [comment]
那可以把你博客的主题代码给我邮箱发一份吗，特别喜欢那个主题，git这里的代码好像和你博客有一丢丢不一样哈，比如图片版权那行字。谢大佬！

**Comment by sollrei** [comment]
把git的更新了一下你看看

**Comment by overbai** [comment]
OK了，真香(￣▽￣)"
